[package]
name = "cal0"
version = "0.1.0"
authors = ["maddiethecafebabe <maddie@cafebabe.date>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "1.4.1"
clap = "2.33.3"
sha2 = "0.9.3"
